# Generated by Django 4.0.5 on 2024-02-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
